### ISSUE TITLE
UNKNOWN_RESULT_STATUS for PrimalStatus in partial_start test

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MosekTools.jl#1]
See https://travis-ci.org/JuliaOpt/MathOptInterfaceMosek.jl/jobs/497225822#L513
I cannot reproduce this locally with my installation (Release 8.1.0.67)

**Comment by ulfworsoe** [comment]
The reason you canot reproduce is that the travis tests use `solve.mosek.com` to solve the problems. This is a way of getting around the license issue. I think it is an issue with Mosek on the server.

**Comment by ulfworsoe** [comment]
I was wrong. The issue is in the local Mosek installation. The issue is present in both MOSEK 8.1 and 9.0-beta, and will be fixed in next build. I'll leave the issue open until a build is out that I can test on.

**Comment by blegat** [comment]
It seems to be resolved :)
