### ISSUE TITLE
Quadratic Objectives not being solved

### ISSUE THREAD

**Issue by rodrigogarciana** [JuliaOpt/MosekTools.jl#2]
When using JuMP v0.19 and MathOptInterfaceMosek.jl, I cannot solve models that I was previously solving with JuMP v0.18 and Mosek.jl
These models have a quadratic objective... I even tried with very simple models (objective such as x[i].^2) but it says that the solver (Mosek) cannot handle Scalar Quadratic objects or something similar.
Do you know what to do? or how should I be writing these functions? Thank you

**Comment by arnavs** [comment]
I'm having this same issue- has it been resolved? Is the above workaround what we should be doing?

**Comment by arnavs** [comment]
Also, I tried the workaround above- 

```
The optimizer supports second-order cone constraints and not quadratic constraints but you entered a quadratic constraint of type: `MathOptInterface.ScalarQuadraticFunction{Float64}`-in-`MathOptInterface.LessThan{Float64}`. A bridge attempted to transform the quadratic constraint to a second order cone constraint but the constraint is not strongly convex, i.e., the symmetric matrix of quadratic coefficients is not positive definite. Convex constraints that are not strongly convex, i.e. the matrix is positive semidefinite but not positive definite, are not supported yet.
```

**Comment by blegat** [comment]
No, objective bridges have not been added, yet, the workaround is still the way to go

**Comment by arnavs** [comment]
Any thoughts on the above error message that I get when I try it?

**Comment by blegat** [comment]
It means that the objective is not convex so it cannot be transformed into a SOC. Which objective did you enter ?

**Comment by arnavs** [comment]
A standard quadratic `z' L z + z' q` for some matrix `L`, vector of variables `z`, and vector of constants `q`.

**Comment by blegat** [comment]
What is eigvals(L + L') ?

**Comment by arnavs** [comment]
Looks like the first one is negative. 

```
  -0.649373433583957  
   0.10460780869676427
   0.1184287900271472 
   0.14145591328958082
   0.17367838622258608
   0.2150827792602814 
   0.2656541849115951 
   0.32537719536705545
   0.3942365802283815 
   0.472217646160893  
   0.5593063290616023 
   0.6554890992764286 
   0.7607527602485178 
   ⋮                  
 166.4033515912563    
 166.50837219324285   
 166.60429916717237   
 166.6911219935768    
 166.76883115135976   
 166.8374181188413    
 166.89687537469132   
 166.9471963987555    
 166.98837567276928   
 167.02040868096367   
 167.04329191056016   
 167.05702285215617   
```

**Comment by arnavs** [comment]
If this specific error message about the cone constraints is just a quirk of the parameters we chose (i.e., the specific `L` matrix), we can choose different ones.

**Comment by blegat** [comment]
The only condition for this to work is all the eigenvalues of `L` should be strictly positive.

**Comment by blegat** [comment]
Because we need to take the cholesky decomposition of L to rewrite it as as a SOC, see e.g. https://en.wikipedia.org/wiki/Second-order_cone_programming#Example:_Quadratic_constraint

**Comment by arnavs** [comment]
Roger that, thanks for clarifying.

**Comment by blegat** [comment]
Objective bridges have been added in MOI v0.9.2
