### ISSUE TITLE
Feature request: MOI.get(Mosek.Optimizer, ::MOI.SolveTime)

### ISSUE THREAD

**Issue by migarstka** [JuliaOpt/MosekTools.jl#25]
Does the Mosek solver return the solve time? If so, it would be great for benchmarks to be able to query the solve time via MOI.

**Comment by mforets** [comment]
I query the solve time with `MOI.get(model, MOI.SolveTime())`, where `model` is a `SOSModel(with_optimizer(Mosek.Optimizer))`.

**Comment by blegat** [comment]
It should work, it is implemented here:
https://github.com/JuliaOpt/MosekTools.jl/blob/aaa8e1e317de9a609ad76788fbfaaef197b82c03/src/attributes.jl#L70

**Comment by migarstka** [comment]
Sorry, didn't see that!
