### ISSUE TITLE
Reading out results fails in a JuMP example

### ISSUE THREAD

**Issue by ketitalabs** [JuliaOpt/MosekTools.jl#3]
This JuMP example [min_ellispe.jl](https://github.com/JuliaOpt/JuMP.jl/blob/master/examples/min_ellipse.jl) uses SCS by default. If you switch it to Mosek, reading out the data after the end of the optimization is broken.
* The `JuMP.primal_status()` is `UNKNOWN_RESULT_STATUS`
* Mosek output on the terminal shows the primal,dual obj value ~6.46, but `JuMP.objective_value()` shows 5.0
* Solution matrix is messed up, too.

**Comment by blegat** [comment]
Mosek 9.0 has been released so closing
