### ISSUE TITLE
UndefVarError: MSK_CT_PEXP not defined

### ISSUE THREAD

**Issue by mlakolar** [JuliaOpt/MosekTools.jl#4]
When using Mosek as a solver, the following error is returned.

> UndefVarError: MSK_CT_PEXP not defined
> 
> Stacktrace:
>  [1] abstractset2ct at /home/mkolar/.julia/packages/MathOptInterfaceMosek/GfJrM/src/constraint.jl:238 [inlined]
>  [2] addbound!(::MosekModel, ::Int64, ::Array{Int64,1}, ::Array{Float64,1}, ::MathOptInterface.ExponentialCone) at /home/mkolar/.julia/packages/MathOptInterfaceMosek/GfJrM/src/constraint.jl:456
>  [3] add_constraint(::MosekModel, ::MathOptInterface.VectorAffineFunction{Float64}, ::MathOptInterface.ExponentialCone) at /home/mkolar/.julia/packages/MathOptInterfaceMosek/GfJrM/src/constraint.jl:78
>  [4] copyconstraints!(::MosekModel, ::MathOptInterface.Utilities.UniversalFallback{JuMP.JuMPMOIModel{Float64}}, ::Bool, ::MathOptInterface.Utilities.IndexMap, ::Type{MathOptInterface.VectorAffineFunction{Float64}}, ::Type{MathOptInterface.ExponentialCone}) at /home/mkolar/.julia/packages/MathOptInterface/QO3Mk/src/Utilities/copy.jl:76
>  [5] default_copy_to(::MosekModel, ::MathOptInterface.Utilities.UniversalFallback{JuMP.JuMPMOIModel{Float64}}, ::Bool) at /home/mkolar/.julia/packages/MathOptInterface/QO3Mk/src/Utilities/copy.jl:109
>  [6] #copy_to#12 at /home/mkolar/.julia/packages/MathOptInterfaceMosek/GfJrM/src/MathOptInterfaceMosek.jl:427 [inlined]
>  [7] (::getfield(MathOptInterface, Symbol("#kw##copy_to")))(::NamedTuple{(:copy_names,),Tuple{Bool}}, ::typeof(MathOptInterface.copy_to), ::MosekModel, ::MathOptInterface.Utilities.UniversalFallback{JuMP.JuMPMOIModel{Float64}}) at ./none:0
>  [8] attachoptimizer!(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{JuMP.JuMPMOIModel{Float64}}}) at /home/mkolar/.julia/packages/MathOptInterface/QO3Mk/src/Utilities/cachingoptimizer.jl:125
>  [9] optimize!(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{JuMP.JuMPMOIModel{Float64}}}) at /home/mkolar/.julia/packages/MathOptInterface/QO3Mk/src/Utilities/cachingoptimizer.jl:158
>  [10] optimize!(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{JuMP.JuMPMOIModel{Float64}}},MathOptInterface.Bridges.AllBridgedConstraints{Float64}}) at /home/mkolar/.julia/packages/MathOptInterface/QO3Mk/src/Bridges/bridgeoptimizer.jl:73
>  [11] #optimize!#96(::Bool, ::Function, ::JuMP.Model, ::Nothing) at /home/mkolar/.julia/packages/JuMP/uAycC/src/optimizer_interface.jl:84
>  [12] macro expansion at /home/mkolar/.julia/packages/JuMP/uAycC/src/optimizer_interface.jl:61 [inlined]

The code is below, where Ψx and Ψy are two matrices.
SCS solver seems to find a solution. 

```
function KLIEP(Ψx, Ψy, solver)
    m, nx = size(Ψx)
    ny = size(Ψy, 2)
    @assert m == size(Ψy, 1)

    lny = log(ny)

    problem = JuMP.Model(solver)
    JuMP.@variable(problem, Θ[1:m])
    JuMP.@variable(problem, t)
    JuMP.@variable(problem, u[1:ny])

    JuMP.@constraint(problem, sum(u) <= 1.)
    for j=1:ny
        JuMP.@constraint(problem, [dot(Θ, Ψy[:, j]) - t - lny, 1., u[j]] in MOI.ExponentialCone())
    end

    JuMP.@objective(problem, Min, -sum(Ψx'*Θ) + t)
    JuMP.optimize!(problem)

    JuMP.result_value.(Θ)
end


solver = JuMP.with_optimizer(MosekOptimizer, QUIET=false)
θhat = KLIEP(Ψx, Ψy, solver)
```

**Comment by Hrj9499** [comment]
I wonder if the problem is solved now. Really don't want switch to another language.

**Comment by blegat** [comment]
Mosek.jl v1.0 has been released a week ago, and it uses Mosek v9 so it should work now.
