### ISSUE TITLE
Indexing of exponential cones does not match MOI convention

### ISSUE THREAD

**Issue by mtanneau** [JuliaOpt/MosekTools.jl#42]
In the [MOI documentation](https://www.juliaopt.org/MathOptInterface.jl/stable/apireference/#MathOptInterface.ExponentialCone), the exponential cone is defined as
```
K = {(x,y,z) | y exp(x/y) ≤ z, y>0}
```
while in [Mosek](https://docs.mosek.com/modeling-cookbook/expo.html) it is defined as
```
K = {(x,y,z) | y exp(z/y) ≤ x, y>0}
```
so the correspondence from MOI to Mosek is `(x, y, z) -> (z, y, x)`.

However that index transformation does not seem to be implemented.

**Comment by blegat** [comment]
It should be implemented:
https://github.com/JuliaOpt/MosekTools.jl/blob/98a27b7b3abcd360731cccee9989c5ffed261ca1/src/attributes.jl#L363-L366
and tests are passing so basic use cases should be covered. Let us know if we missed a corner case.

**Comment by mtanneau** [comment]
Turns out my issue was index-related, but it came from my part of the code. Sorry about the noise.
