### ISSUE TITLE
Getting ObjectiveFunction only works with Mosek master

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MosekTools.jl#9]
It uses `getclist`:
https://github.com/JuliaOpt/MathOptInterfaceMosek.jl/blob/7b45398c903a400bec0cb6a7eb14e15cb01497f5/src/objective.jl#L7
which is only available in Mosek master and the latest release.
@ulfworsoe Is it a feature that have been added in Mosek 9 ?

**Comment by ulfworsoe** [comment]
I have added a `getclist` function to `Mosek.jl` branch `b0.9`, released as `v0.9.10`. This should in principle fix it.

**Comment by blegat** [comment]
It now works and is tested in https://github.com/JuliaOpt/MosekTools.jl/pull/23
